<a href="https://colab.research.google.com/github/Src-Bhavesh/DS-Basics/blob/main/06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas**

In [4]:
import pandas as pd
dct ={
    'name':['Tom','Nick','Krish','Jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]
}
# df = pd.DataFrame(dct)
df = pd.DataFrame(dct,index=['a','b','c','d'])
# print(df)
# df
display(df)
display(df)

    name  age  roll
a    Tom   20     1
b   Nick   21     2
c  Krish   19     3
d   Jack   18     4

    name  age  roll
a    Tom   20     1
b   Nick   21     2
c  Krish   19     3
d   Jack   18     4

In [5]:
df = pd.read_csv('./student_data.csv')

df.head(3)
df.tail(3)

df.shape

df.info()

df.describe()

df.columns

df.dtypes

df.index

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [7]:
df = pd.read_csv('./student_data.csv')

df[['study_hours','internet_usage']]

df.study_hours

df.iloc[0:10]

# df.loc[df['study_hours']==11,['attendance','placement_status','study_hours']]
df.loc[df['study_hours']==11,['attendance','placement_status','study_hours']].iloc[4:8]

df2= df.loc[df['study_hours']]
df2[['study_hours','sleep_hours']]

df2.iloc[10:20]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
11,8,65,5,6,4,87,100.00,Placed
8,7,72,8,5,18,48,96.81,Placed
5,7,40,9,10,0,60,72.33,Placed
4,5,52,8,6,8,40,78.82,Placed
8,7,72,8,5,18,48,96.81,Placed
8,7,72,8,5,18,48,96.81,Placed
3,8,99,9,8,4,55,90.17,Placed
6,10,40,4,11,9,50,98.12,Placed
5,7,40,9,10,0,60,72.33,Placed
2,11,60,7,6,10,45,100.00,Placed

In [ ]:
df = pd.read_csv('./student_data.csv')

df.loc[df['assignments_completed']==8].iloc[1]

# df.loc[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
d={
    'name':['Tom','Nick','Krish','Jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,None]
}
df1 = pd.DataFrame(d)


df = pd.read_csv('./student_data.csv')
df['age']=20;
df

df.rename(columns={'assignments_completed':'assign_complete'},inplace = True)

df.drop('sleep_hours', axis=1)
df.drop(1,axis=0)

df1.dropna()

# df.sort_values('study_hours')
df.sort_index()

df1.isnull()

df1.notnull()

df1.fillna(0)

df['attendance'].unique()

array([ 56,  69,  60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,
        76,  80,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,
        42,  58,  82,  68,  89,  41,  48,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])