<a href="https://colab.research.google.com/github/Src-Bhavesh/DS-Basics/blob/main/07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas**

In [2]:
import pandas as pd
df = pd.read_csv('./student_data.csv')

In [8]:
df.groupby('placement_status')['placement_status'].agg('count')
df.groupby('placement_status')['sleep_hours'].agg('mean')
df.groupby('placement_status').agg(mean=('placement_status','count'),avg=('sleep_hours','mean'))

                  mean       avg
placement_status
Not Placed        1644  6.072384
Placed            8356  6.582336

In [16]:
df.groupby('placement_status').agg(mean=('study_hours','mean'))

                      mean
placement_status
Not Placed        3.130170
Placed            6.552178

In [17]:
df.groupby('study_hours').agg(placement=('placement_status','count'),Sleep=('sleep_hours','mean'))

             placement     Sleep
study_hours
1                  936  6.476496
2                  909  6.525853
3                  899  6.525028
4                  890  6.495506
5                  886  6.531603
6                  938  6.446695
7                  926  6.515119
8                  890  6.561798
9                  903  6.472868
10                 955  6.474346
11                 868  6.461982

In [14]:
df.groupby('placement_status').agg(Mean=('exam_score','mean'))

                       Mean
placement_status
Not Placed        59.804653
Placed            91.996556

In [19]:
df.groupby('study_hours').agg(score=('exam_score','mean'))

                 score
study_hours
1            71.264562
2            75.169142
3            78.974939
4            81.845483
5            84.964142
6            88.620043
7            90.539568
8            93.297697
9            95.462126
10           96.574628
11           97.303283

In [20]:
def grade(x):
  if x>90:
    return 'A'

  elif x>80:
    return 'B'

  elif x>70:
    return 'C'

  elif x>50:
    return 'D'

  elif x>35:
    return 'E'

  else :
    return 'F'

df['Grade'] = df['exam_score'].apply(grade)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,Grade
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,C
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,D
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,B
9999,2,70,6,11,16,52,78.96,Placed,C