<a href="https://colab.research.google.com/github/Src-Bhavesh/DS-Basics/blob/main/08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

In [16]:

df1 = pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})


df3 = pd.merge(df1,df2,on='id',how='inner')
df3.rename(columns={'name_x':'Name-1'},inplace=True)
print(df3)
print('\n')

df4 = pd.merge(df1,df2,on='id',how='left')
print(df4)
print('\n')

df5 = pd.merge(df1,df2,on='id',how='right')
print(df5)
print('\n')

df6 = pd.merge(df1,df2,on='id',how='outer')
print(df6 )
print('\n')

df7 = pd.merge(df1,df2,how='cross')
print(df7)

   id Name-1  age_x name_y  age_y
0   3  Rahul     35  Rahul     35
1   4   Rhea     40   Rhea     40


   id name_x  age_x name_y  age_y
0   1   Raja     25    NaN    NaN
1   2   Rani     30    NaN    NaN
2   3  Rahul     35  Rahul   35.0
3   4   Rhea     40   Rhea   40.0


   id name_x  age_x name_y  age_y
0   3  Rahul   35.0  Rahul     35
1   4   Rhea   40.0   Rhea     40
2   5    NaN    NaN   Ravi     45
3   6    NaN    NaN  Reena     50


   id name_x  age_x name_y  age_y
0   1   Raja   25.0    NaN    NaN
1   2   Rani   30.0    NaN    NaN
2   3  Rahul   35.0  Rahul   35.0
3   4   Rhea   40.0   Rhea   40.0
4   5    NaN    NaN   Ravi   45.0
5   6    NaN    NaN  Reena   50.0


    id_x name_x  age_x  id_y name_y  age_y
0      1   Raja     25     3  Rahul     35
1      1   Raja     25     4   Rhea     40
2      1   Raja     25     5   Ravi     45
3      1   Raja     25     6  Reena     50
4      2   Rani     30     3  Rahul     35
5      2   Rani     30     4   Rhea     40
6      2   Rani     30     5   Ravi     45
7      2   Rani     30     6  Reena     50
8      3  Rahul     35     3  Rahul     35
9      3  Rahul     35     4   Rhea     40
10     3  Rahul     35     5   Ravi     45
11     3  Rahul     35     6  Reena     50
12     4   Rhea     40     3  Rahul     35
13     4   Rhea     40     4   Rhea     40
14     4   Rhea     40     5   Ravi     45
15     4   Rhea     40     6  Reena     50

In [19]:
df1 = pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

df3 = pd.concat([df1,df2])   #should have same no. of column
print(df3)
print('\n')

   id   name  age
0   1   Raja   25
1   2   Rani   30
2   3  Rahul   35
3   4   Rhea   40
0   3  Rahul   35
1   4   Rhea   40
2   5   Ravi   45
3   6  Reena   50

In [27]:
df = pd.DataFrame({
    'name':['a','d','c','a','b','d'],
    'age':[1,2,3,4,2,2]
})
print(df)

df=df.drop_duplicates(); #drop only is entire row is a duplicate
print(df)

df=df.drop_duplicates(subset=['name'],keep='first') #keep first or last
print(df)

  name  age
0    a    1
1    d    2
2    c    3
3    a    4
4    b    2
5    d    2
  name  age
0    a    1
1    d    2
2    c    3
3    a    4
4    b    2
  name  age
0    a    1
1    d    2
2    c    3
4    b    2

In [34]:
df = pd.read_csv('./student_data.csv');
# print(df)

df.pivot_table(columns='placement_status',index='sleep_hours',values='exam_score' , aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [33]:
df = pd.read_csv('./student_data.csv');
# print(df)

df.pivot_table(columns='study_hours',index='sleep_hours',values='assignments_completed' , aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844